name: Branch Protection

on:
  pull_request:
    branches: [main, staging]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check merge rules
        run: |
          TARGET="${{ github.base_ref }}"
          SOURCE="${{ github.head_ref }}"
          
          echo "Source branch: $SOURCE"
          echo "Target branch: $TARGET"
          
          echo "âœ… Branch merge rules validated."
